services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Africa/Accra
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_WEBHOOK_URL=http://192.168.56.116:5678/
      - N8N_SECURE_COOKIE=false
      - TZ=Africa/Accra
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
